# Generated by Django 4.2.4 on 2023-10-28 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
        ('Workshops', '0001_initial'),
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attended_events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='Workshops.workshop'),
        ),
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.club'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.hostel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together={('user', 'subject')},
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('isSecy', True)), fields=('club',), name='One Secretory for one club'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('isRep', True)), fields=('hostel', 'club'), name='One Representative of club for one hostel'),
        ),
    ]
