# Generated by Django 4.2.7 on 2023-11-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfinitesimalURL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='last_visited',
        ),
    ]
