# Generated by Django 4.2.4 on 2023-10-28 15:49

import Workshops.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('poster', models.ImageField(default='images/default.jpg', upload_to=Workshops.models.upload_path)),
                ('venue', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('description', models.TextField(max_length=1200)),
                ('duration', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=models.SET(Workshops.models.get_superadmim), to='Users.profile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.club')),
                ('hostel', models.ManyToManyField(to='Database.hostel')),
            ],
        ),
    ]
