# Generated by Django 4.2.4 on 2023-10-22 15:46

import Workshops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='added_by',
            field=models.ForeignKey(on_delete=models.SET(Workshops.models.get_superadmim), to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to=Workshops.models.upload_path),
        ),
    ]
