# Generated by Django 4.2.7 on 2023-11-02 19:33

import Database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('board', models.CharField(choices=[('BRCA', 'BRCA'), ('BHM', 'BHM'), ('BSA', 'BSA'), ('BSW', 'BSW')], default='BRCA', max_length=50)),
                ('logo', models.ImageField(default='Database/Club/logo/default.jpg', upload_to=Database.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('college_city', models.CharField(max_length=100)),
                ('college_state', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('college_name', 'college_city', 'college_state')},
            },
        ),
    ]
